server:
  port : 8082
  servlet :
    context-path: /demo1


spring:
  datasource:
    url: jdbc:mysql://docker-sql:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update